### ISSUE TITLE
Router is reporting "Not Found" errors

### ISSUE THREAD

**Issue by harryzcy** [harryzcy/mailbox-browser#1163]
Error start to occur after 47f22da

**Comment by harryzcy** [comment]
React router issue: https://github.com/remix-run/react-router/issues/11484

**Comment by harryzcy** [comment]
Maybe related to https://github.com/rollup/rollup/issues/5484?

**Comment by liuly0322** [comment]
> Error start to occur after [47f22da](https://github.com/harryzcy/mailbox-browser/commit/47f22da4b3a1426c0d268f3e0e051acbbde602ed)

Would you please update to `4.16.2` and verify if it's ok? The bug for react router should be fixed. If you are not sure, maybe override `rollup` to `4.15` in your package.json.
