### ISSUE TITLE
Serverless support

### ISSUE THREAD

**Issue by hellodword** [harryzcy/mailbox-browser#482]
Hi, really want to deploy this project on Cloudflare Workers[^1]/Pages[^2], but I found it's marked as `not planned` in #74, any reason for that?

[^1]: https://workers.cloudflare.com/
[^2]: https://pages.cloudflare.com/

**Comment by harryzcy** [comment]
Glad that you bring this up. It's only because I'm using docker myself anyways, so I prioritized my time elsewhere.

But I can try with cloudflare. I'm using some cloudflare products as well.

**Comment by harryzcy** [comment]
It's now supported using Cloudflare Pages and Pages Functions. You can run `make cloudflare` to deploy, which will 1) build the frontend, 2) copy `dist` folder into `cloudflare/dist`, 3) deploy using `wrangler`.
